server:
  port:


spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    #    url:
    #    username:
    #    password:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    # show-sql: true  # ?? ??? ??? ???? ??
    # ??? ?? ? ?? ??? ?? ???? ??
    database-platform:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        format_sql:
    database:
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable:
          auth:

logging.level:
  org.hibernate.SQL:

# swagger setting
springdoc:
  swagger-ui:
    path:

# Json Web Token setting
jwt:
  secret:

# sns login data
sns:
  kakao:
    app-key:
    redirect-uri:

upload:
  path:
    project:
    profile:

#s3 접근 설정
aws:
  credentials:
    accessKey:
    secretKey:
  region:
  bucketName: